---
- name: Manage User Shells
  hosts: your_servers
  become: yes  # 更改用户信息需要 root 权限

  tasks:
    - name: logout all users
      shell: pkill -KILL -u {{ item }}
      loop:
        - day1
      ignore_errors: yes  # 如果用户未登录，忽略错误
