- name: Ensure ufw is installed
  ansible.builtin.apt:
    name: ufw
    state: present
    update_cache: yes

- name: Reset ufw rules (clean start)
  ansible.builtin.command: ufw --force reset

- name: Set default policy to deny incoming
  ansible.builtin.ufw:
    state: enabled
    policy: deny
    direction: incoming

- name: Set default policy to deny outgoing
  ansible.builtin.ufw:
    state: enabled
    policy: deny
    direction: outgoing

- name: Allow DNS (UDP)
  ansible.builtin.ufw:
    rule: allow
    port: 53
    proto: udp

- name: Allow DNS (TCP)
  ansible.builtin.ufw:
    rule: allow
    port: 53
    proto: tcp

- name: Allow outgoing HTTP (80/tcp) to allowed hosts
  ansible.builtin.ufw:
    rule: allow
    to_ip: "{{ item.ip }}"
    port: 80
    proto: tcp
  loop: "{{ allowed_hosts }}"